#!/bin/bash
# if [[ $(ip addr | grep eth0) == '' ]]; then echo "eth0 down"; else ip addr show dev eth0 | grep "inet\b" | awk '{print "eth0: " $2}' | cut -d/ -f1; fi
ip=`ip a s eth0 2>/dev/null | grep -o -P "(?<=inet )[0-9]{1,3}(\.[0-9]{1,3}){3}"`
if [[ $(ip addr | grep tun0) == '' ]]; then echo "Status Down"; else echo "eth0: "$ip; fi