#!/bin/bash
#if [[ $(ip addr | grep eth0) == '' ]]; then echo "eth0 down"; else ip addr show dev eth0 | grep "inet\b" | awk '{print "eth0: " $2}' | cut -d/ -f1; fi
ip1=`ip a s eth0 2>/dev/null | grep -o -P '(?<=inet )[0-9]{1,3}(\.[0-9]{1,3}){3}'`
ip2=`ip a s ens33 2>/dev/null | grep -o -P '(?<=inet )[0-9]{1,3}(\.[0-9]{1,3}){3}'`
if [[ $(ip addr | grep eth0) == '' ]]; then echo "ens33: "$ip2 ; else echo "eth0: "$ip1; fi
