#!/bin/bash
# tun0
# if [[ $(ip addr | grep tun0) == '' ]]; then echo "Status Down"; else ip addr show dev tun0 | grep "inet\b" | awk '{print "tun0: " $2}'| cut -d/ -f1; fi
ip=`ip a s tun0 2>/dev/null | grep -o -P "(?<=inet )[0-9]{1,3}(\.[0-9]{1,3}){3}"`
if [[ $(ip addr | grep tun0) == '' ]]; then echo "Status Down"; else echo "tun0: "$ip; fi